apiVersion: v1
kind: Secret
metadata:
  name: tradingbot-secrets
  namespace: tradingbot
type: Opaque
data:
  JWT_SECRET: UkVQTEFDRV9NRV9KU1Q= # base64(REPLACE_ME_JWT)
  ENCRYPTION_KEY: UkVQTEFDRV9NRV9FTkNSWVBUSU9O # base64(REPLACE_ME_ENCRYPTION_KEY)
  DATABASE_URL: UkVQTEFDRV9NRV9EQVRBQkFTRV9VUkw= # base64(REPLACE_ME_DATABASE_URL)
  DATABASE_DIRECT_URL: UkVQTEFDRV9NRV9ESVJFQ1RfVVJM # base64(REPLACE_DIRECT_URL)
  DATABASE_SHADOW_URL: UkVQTEFDRV9NRV9TSEFET1dfVVJM # base64(REPLACE_SHADOW_URL)
  BSC_RPC_URL: UkVQTEFDRV9NRV9CU0NfUlBD # base64(REPLACE_ME_BSC_RPC)
  BSC_TESTNET_RPC: UkVQTEFDRV9NRV9CU0NfVEVTVF9SUEM= # base64(REPLACE_ME_BSC_TESTNET_RPC)
  BSCSCAN_API_KEY: UkVQTEFDRV9NRV9CU0NfQVBJ # base64(REPLACE_ME_BSCSCAN_API_KEY)

